# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: BuildAndDeployWebApplication1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  Build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master
       
    - uses: microsoft/variable-substitution@v1 # https://docs.microsoft.com/en-us/azure/developer/github/github-variable-substitution
      with:
          files: './src/WebApplication1/appsettings.json'
      env:
          SETTING1: "I am Setting1 from Azure appsettings.json"
          SETTING2: "I am Setting2 from Azure appsettings.json"
          SETTING3: ""
       
    - uses: microsoft/variable-substitution@v1 # https://docs.microsoft.com/en-us/azure/developer/github/github-variable-substitution
      with:
          files: './src/WebApplication1/appsettings.Development.json'
      env:
          SETTING1: "I am Setting1 from Azure appsettings.Development.json"
          SETTING3: ""
      
    - uses: azure/docker-login@v1
      with:
        login-server: https://${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USER_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      run : |
        docker build -f ./src/WebApplication1/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_USER_NAME }}/webapplication1:${{ env.VERSION }} ./src

    - name: Deploy image to container registry
      run : |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_USER_NAME }}/webapplication1:${{ env.VERSION }}
        
  Deploy:
    runs-on: 'ubuntu-latest'
    needs: Build

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}        
        enable-AzPSSession: true 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PRODUCT_ID }}01app
        images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_USER_NAME }}/webapplication1:${{ env.VERSION }}'      

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PRODUCT_ID }}01app
        mask-inputs: false
        app-settings-json: '[{ "name": "SETTING3", "value": "I am Setting3 from Docker environment", "slotSetting": false }]'
